# Generated by Django 4.1.4 on 2023-07-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images.jpeg', null=True, upload_to='profiles'),
        ),
    ]
