# Generated by Django 4.1.4 on 2023-07-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmodel_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isonline',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
