# Generated by Django 4.1.4 on 2023-07-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatnotification',
            name='is_seen',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
